autodiff/autodiff/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('diffapp.urls'))
]

autodiff/diffapp/urls.py
from django.urls import path
from . import views
app_name = 'diff'

urlpatterns = [
    path('', views.get_version),
    path('display/', views.display, name='display')
]

autodiff/diffapp/models.py
from django.db import models

# Create your models here.

autodiff/diffapp/forms.py
from django import forms

class GetVersionForm(forms.Form):
    whichapp = [
        ('magento', 'magento'),
        ('prestashop', 'prestashop'),
        ('wordpress', 'wordpress'),
        ('joomla', 'joomla')
    ]
    version1 = [
        ('2.3.2', 'Magento 2.3.2'),
        ('2.3.1', 'Magento 2.3.1'),
        ('2.3.0', 'Magento 2.3.0'),
        ('2.2.9', 'Magento 2.2.9'),
        ('2.2.8', 'Magento 2.2.8'),
        ('1.7.6.0', 'Prestashop 1.7.6.0'),
        ('1.7.5.2', 'Prestashop 1.7.5.2'),
        ('5.2.2', 'Wordpress 5.2.2'),
        ('5.2.1', 'Wordpress 5.2.1'),
        ('3.9.11', 'Joomla 3.9.11'),
        ('3.9.10', 'Joomla 3.9.10')
    ]
    which_app = forms.ChoiceField(choices=whichapp, label="Which application do you want to compare: ")

    version_1 = forms.ChoiceField(choices=version1, label='Input version 1 to get be compared against')
    version_2 = forms.ChoiceField(choices=version1, label='Input version 2 to be compared against')

autodiff/diffapp/views.py
from django.shortcuts import render
import filecmp, difflib
import os
# import time

from .helpers import download
from .compare import getdiff
from .forms import GetVersionForm
from .config import (
    directory_names, IGNORE_FILES_MAGENTO,
    IGNORE_FILES_PRESTASHOP, _filter
)

# to be imported from config.py
filecmp._filter = _filter

def get_version(request):
    # start = time.time()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = GetVersionForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            return display(request)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = GetVersionForm()

    return render(request, 'diffapp/diffapp.html', {'form': form})

def display(request):
    output = []
    # process version entered by user
    version_1 = request.POST['version_1']
    version_2 = request.POST['version_2']
    which_app = request.POST['which_app']


    # compare dirs
    version_list = [version_1, version_2]
    if which_app.lower() == "magento":

        dir1_name = "magento2-" + version_1
        dir2_name = "magento2-" + version_2
        dir_to_compare = [dir1_name, dir2_name]

        # directory_1, directory_2 = dir_to_compare

        # check if applications are already downloaded
        result = all(elem in directory_names for elem in dir_to_compare)

        if result:
            """function compare is called """
            print("Comparing all files in each directories ......\n")
            dcmp = filecmp.dircmp(dir1_name + '/app/code/magento', dir2_name + '/app/code/magento',
                                  ignore=IGNORE_FILES_MAGENTO)

            print("Please give me a second until i write the diff in an html file ......\n")

            output = getdiff(dcmp, which_app.lower())
        else:
            """function download is called """
            download(version_list, which_app.lower())

            print("Comparing all files in each directories ......\n")

            dcmp = filecmp.dircmp(dir1_name + '/app/code/magento', dir2_name + '/app/code/magento',
                                  ignore=IGNORE_FILES_MAGENTO)

            print("Please give me a second until i write the diff in an html file ......\n")

            output = getdiff(dcmp, which_app.lower())
            # end = time.time()

            # print("Diff processing is complete with in %s seconds" % (end - start))

    elif which_app.lower() == "prestashop":
        dir1_name = "PrestaShop-" + version_1
        dir2_name = "PrestaShop-" + version_2
        dir_to_compare = [dir1_name, dir2_name]
        # directory_1, directory_2 = dir_to_compare
        # check if applications are already downloaded
        result = all(elem in directory_names for elem in dir_to_compare)

        if result:
            """function compare is called """

            print("Comparing all files in each directories ......\n")

            dcmp = filecmp.dircmp(dir1_name, dir2_name,
                                    ignore=IGNORE_FILES_PRESTASHOP)

            print("Please give me a second until i write the diff in an html file........ \n")

            output = getdiff(dcmp, which_app.lower())
            
        else:
            """function download is called """
            download(version_list, which_app.lower())

            print("Comparing all files in each directories ......\n")

            dcmp = filecmp.dircmp(dir1_name, dir2_name,
                                    ignore=IGNORE_FILES_PRESTASHOP)
            
            print("Please give me a second until i write the diff in an html file ...... \n")
            
            output = getdiff(dcmp, which_app.lower())
    elif which_app.lower() == "wordpress":
        dir1_name = "wordpress-" + version_1
        dir2_name = "wordpress-" + version_2
        dir_to_compare = [dir1_name, dir2_name]
        # directory_1, directory_2 = dir_to_compare
        # check if applications are already downloaded
        result = all(elem in directory_names for elem in dir_to_compare)

        if result:
            """function compare is called """

            print("Comparing all files in each directories ......\n")
            directory1 = os.path.dirname(dir1_name + '/wordpress')
            directory2 = os.path.dirname(dir2_name + '/wordpress')
            dcmp = filecmp.dircmp(directory1, directory2,
                                    ignore=IGNORE_FILES_PRESTASHOP)

            print("Please give me a second until i write the diff in an html file........ \n")

            output = getdiff(dcmp, which_app.lower())
            
        else:
            """function download is called """
            download(version_list, which_app.lower())

            print("Comparing all files in each directories ......\n")
            directory1 = os.path.dirname(dir1_name + '/wordpress')
            directory2 = os.path.dirname(dir2_name + '/wordpress')
            dcmp = filecmp.dircmp(directory1, directory2,
                                    ignore=IGNORE_FILES_PRESTASHOP)
            
            print("Please give me a second until i write the diff in an html file ...... \n")
            
            output = getdiff(dcmp, which_app.lower())

    return render(request, 'diffapp/display.html', {'files': output, 'which_app': which_app, 'version_1': version_1, 'version_2': version_2})

autodiff/diffapp/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
    <title>Diff app</title>
  </head>
  <body class="template-index template-index-min">
        <div class="container">
          <h1 class="mt-4">Diff App</h1>
          {% comment %} <p>This is a simple app designed to minimize the time during filtering an application such as Magento by excluding unnecessary files, and directories</p> {% endcomment %}
        </div>
        <br>
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <!-- form block -->
            {% block form %}
            {% endblock form %}
          </div>
          <div class="col-md-6 offset-11">
          {% block filter %}
          {% endblock %}
          </div>
        </div>
        <div class="row" style="width:80">
          <!-- content block -->
        {% block content %}
        {% endblock content %}
        </div>
      </div>
    
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="{% static 'js/jquery.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <script src="{% static 'js/custom.js' %}"></script>
  </body>
</html>

autodiff/diffapp/templates/diffapp/diffapp.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block form %}
    <form action="{% url 'diff:display' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input id="url-btn" type="submit" value="Submit" class="btn btn-primary">
    </form>
{% endblock form %}
{% block filter %}
    <button class="btn btn-secondary">Click to check infected files</button>
{% endblock %}

autodiff/diffapp/templates/diffapp/display.html
{% extends "base.html" %}
{% load static %}
{% load autodiff_extras %}
{% block content %}
<h4 class="card-title" style="align:center">{{ which_app }} Diff between {{version_1}} and {{ version_2}}</h4>
<div></div>
<br/><br/>

{% for file in files %}
<div class="diff" style="width: 1514px;">
<pre class=".prettyprint">
{% for line in file %}{% if forloop.first %}<div class="collapsible">{{ line|replace:"/\w+\d?-\d?.\d?.\d/"}}</div>{% endif %}{% if line|first in '-'%}<div class="row diff_padding">{{" "}}<span class="diff_sub">{{ line }}</span></div>{% endif %}{% if line|first in '+'%}<div class="row diff_padding">{{" "}}<span class="diff_add">{{ line }}</span></div>{% endif %}{% endfor %}
</pre>
</div>
<br>
{% endfor %}
{% endblock content %}